apiVersion: v1
kind: Service
metadata:
  name: northstar-core-api
  namespace: northstar
  labels:
    app.kubernetes.io/name: northstar-bank
    app.kubernetes.io/component: core-api
spec:
  selector:
    app.kubernetes.io/name: northstar-bank
    app.kubernetes.io/component: core-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: northstar-core-api
  namespace: northstar
  labels:
    app.kubernetes.io/name: northstar-bank
    app.kubernetes.io/component: core-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: northstar-bank
      app.kubernetes.io/component: core-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: northstar-bank
        app.kubernetes.io/component: core-api
    spec:
      initContainers:
        - name: migrate
          image: 942909611186.dkr.ecr.us-east-1.amazonaws.com/northstar-core-api:sha-ad99e0b2b1e5e07bdebd4a0cc88eb0a31d8d0450
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "until alembic upgrade head; do echo waiting for database; sleep 3; done"]
          envFrom:
            - configMapRef:
                name: northstar-config
            - secretRef:
                name: northstar-database
        - name: seed
          image: 942909611186.dkr.ecr.us-east-1.amazonaws.com/northstar-core-api:sha-ad99e0b2b1e5e07bdebd4a0cc88eb0a31d8d0450
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "scripts.seed"]
          envFrom:
            - configMapRef:
                name: northstar-config
            - secretRef:
                name: northstar-database
      containers:
        - name: core-api
          image: 942909611186.dkr.ecr.us-east-1.amazonaws.com/northstar-core-api:sha-ad99e0b2b1e5e07bdebd4a0cc88eb0a31d8d0450
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: northstar-config
            - secretRef:
                name: northstar-database
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
