apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: northstar-aws-secrets
  namespace: northstar
  labels:
    app.kubernetes.io/name: northstar-bank
    environment: dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: northstar-database
  namespace: northstar
  labels:
    app.kubernetes.io/name: northstar-bank
    environment: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: northstar-aws-secrets
  target:
    name: northstar-database
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: Northbank-secret
