apiVersion: v1
kind: Service
metadata:
  name: northstar-postgresql
  namespace: northstar
  labels:
    app.kubernetes.io/name: northstar-bank
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: northstar-bank
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: northstar-postgresql
  namespace: northstar
  labels:
    app.kubernetes.io/name: northstar-bank
    app.kubernetes.io/component: postgresql
spec:
  serviceName: northstar-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: northstar-bank
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: northstar-bank
        app.kubernetes.io/component: postgresql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgresql
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgresql
              containerPort: 5432
          envFrom:
            - secretRef:
                name: northstar-database
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 5Gi
