replicas: 1

testFramework:
  enabled: false

service:
  type: ClusterIP

ingress:
  enabled: false

persistence:
  enabled: true
  storageClassName: gp3
  size: 2Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
        editable: false
